---
  - name: RABBITMQ - install Erlang 21.2
    yum:
      name: https://github.com/rabbitmq/erlang-rpm/releases/download/v21.3.8.6/erlang-21.3.8.6-1.el7.x86_64.rpm
      state: present
    register: erlang_result

  - name: RABBITMQ - install RabbitMQ 3.7
    yum:
      name: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.12/rabbitmq-server-3.7.12-1.el7.noarch.rpm
      state: present
    register: rabbitmq_result

  - name: RABBITMQ - enable and start RabbitMQ
    systemd:
      name: rabbitmq-server
      enabled: yes
      state: started

  - name: RABBITMQ - enable RabbitMQ Management Plugin
    command: rabbitmq-plugins enable rabbitmq_management
    when: rabbitmq_result.changed

  - name: RABBITMQ - add a host `{{ansible_nodename}}`
    command: rabbitmqctl add_vhost {{ansible_nodename}}
    when: rabbitmq_result.changed

  - name: RABBITMQ - create a user {{rabbitmq_user}}@{{ansible_nodename}} and set his permissions
    rabbitmq_user:
      user: "{{rabbitmq_user}}"
      password: "{{rabbitmq_password}}"
      tags: "{{rabbitmq_user_tag}}"
      vhost: "{{ansible_nodename}}"
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      state: present

#  - debug:
#      var: httpd_result

#  - debug:
#      var: hostvars