---
  - name: RABBITMQ - install Erlang 21.2
    yum:
      name: https://bintray.com/rabbitmq-erlang/rpm/download_file?file_path=erlang%2F21%2Fel%2F7%2Fx86_64%2Ferlang-21.2.6-1.el7.x86_64.rpm
      state: present
    register: erlang_result

  - name: RABBITMQ - upload RabbitMQ repository information into /etc/yum.repos.d/rabbitmq.repo
    template:
      src: etc/yum.repos.d/rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo
      owner: root
      group: root
      mode: 0644

  - rpm_key:
      state: present
      key: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc

  - name: RABBITMQ - install RabbitMQ 3.7
    yum:
#      name: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.12/rabbitmq-server-3.7.12-1.el7.noarch.rpm
      name: rabbitmq-server-3.7.12-1.el7.noarch.rpm
      state: present
    register: rabbitmq_result

  - name: RABBITMQ - enable and start RabbitMQ
    systemd:
      name: rabbitmq-server
      enabled: yes
      state: started

  - name: RABBITMQ - enable RabbitMQ Management Plugin
    command: rabbitmq-plugins enable rabbitmq_management
    when: rabbitmq_result.changed

#  - debug:
#      var: httpd_result

#  - debug:
#      var: hostvars